import { Box } from "@mui/material";
import InternationalTournament from "./[matchId]/(page)";

export const metadata = {
  title: "International Tournaments",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <InternationalTournament />
      {children}
      <Box className='footerBackSide'></Box>
    </>
  )
}