import { Box } from "@mui/material";
import Tournament from "./[id]/(page)";

export const metadata = {
  title: "Tournaments",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Tournament />
      {children}
      <Box className='footerBackSide'></Box>
    </>
  )
}