'use client'
import SvgDefs from "@/assets/icons/icons";
import Reduxprovider from "@/redux/ReduxProvider";
import { Box } from "@mui/material";
import { ThemeProvider } from '@mui/material/styles';
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { Footer } from "../components/common/commonUi/Footer/Footer";
import { theme } from "../components/common/theme";
import "./globals.css";

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const [shouldHideFooter, setShouldHideFooter] = useState(false);
  const [shouldHide, setShouldHide] = useState(false);
  // const [loading, setLoading] = useState(false);
  const params = useParams()

  // useEffect(() => {
  //   if (typeof window !== "undefined") {
  //     import("next/router").then((nextRouter) => {
  //       const router = nextRouter.default;
  //       const handleStart = () => {
  //         setLoading(true)
  //       };
  //       const handleComplete = () => setLoading(false);

  //       router.events.on("routeChangeStart", handleStart);
  //       router.events.on("routeChangeComplete", handleComplete);
  //       router.events.on("routeChangeError", handleComplete);

  //       return () => {
  //         router.events.off("routeChangeStart", handleStart);
  //         router.events.off("routeChangeComplete", handleComplete);
  //         router.events.off("routeChangeError", handleComplete);
  //       };
  //     });

  //     const handleButtonClick = (event) => {
  //       if (event.target.tagName === "BUTTON") {
  //         setLoading(true);
  //         setTimeout(() => {
  //           setLoading(false);
  //         }, 1000); 
  //       }
  //     };

  //     document.body.addEventListener("click", handleButtonClick);

  //     return () => {
  //       document.body.removeEventListener("click", handleButtonClick);
  //     };

  //   }
  // }, []);

  useEffect(() => {
    UpdatePath()
  }, [params]);


  const UpdatePath = () => {
    const path = window.location.pathname;
    const pathsToHideFooter = ['/toss', '/player11', '/scoreboard', '/playerboard', '/players/', '/creatematch', '/automatchschedule', '/registeredTornaments', '/edit-match', '/edit-tournament', '/teams/', '/login', '/create-auction-player', '/live-auction/', '/live-auction-view/'];
    const pathsForHide = ['/mytournament', '/tournament'];
    const shouldHide = pathsToHideFooter.some((p) => path.includes(p));
    const shouldHidePad = pathsForHide.some((p) => path.includes(p));
    setShouldHide(shouldHidePad)
    setShouldHideFooter(shouldHide);
  }

  // if (loading) return <Loader/>
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <SvgDefs />
        <ThemeProvider theme={theme}>
          <Reduxprovider>
            <Box sx={{
              background: 'var(--background-forever) !important',
              color: 'var(--primary-color)',
              minHeight: '100vh',
              maxWidth: 'var(--screen-max-width)',
              margin: '0 auto'
            }}>
              {/* <Box className='firstPagePreview'></Box> */}
              <Box className={!shouldHideFooter && 'main-container'} id='mainContainer'>
                {children}
              </Box>
              {!shouldHideFooter &&
                <>
                  {/* <Box className='footerBackSide'></Box> */}
                  <Footer />
                </>
              }
            </Box>
          </Reduxprovider>
        </ThemeProvider>
      </body>
    </html>
  );
}
