export const CommonText = {

    BowlerStrikesAndBatterWalkOff: " LBW! The bowler strikes, and the batter walks off!",
    BallStumpsBowledBattersOut: 'The ball takes the stumps—bowled, the batter’s out!',
    CatchBatterdismissed: 'catches batter dismissed spectacularly!',
    RunOut: 'Run out! A direct hit by',
    StumpedOut: 'Stumped out! A sharp take by',
    TimingAndRunScore: ' Perfect timing, four runs scored!',
    SixCrowdGoesWild: 'What a six! Crowd goes wild!',
    AddPlayerContinue: 'Please Add More Players to Continue',
    Commentary: 'Commentary',
    Score: 'Score',
    NoCommentaryAvailable: 'No commentary available',
    SelectTeam1: 'Select Team 1',
    SelectTeam2: 'Select Team 2',
    ScheduleMatch: 'Schedule Match',
    ErrorTeam1Team2NotSame: 'Team 1 and Team 2 cannot be the same.',
    Team1Required: 'Team 1 is required',
    Team2Required: 'Team 2 is required',
    SelectTeam: 'Select Team',
    ErrorUploadImage: "Failed to upload images. Please try again.",
    BattingTeam: 'Batting Team',
    BowlingTeam: 'Bowling Team',
    SelectStriker: 'Select Striker',
    NonStriker: 'Non Striker',
    SelectBowler: 'Select Bowler',
    SelectNonStriker: 'Select Non-striker',
    StartScoring: 'Start Scoring',
    AddPlayer: 'Add Player',
    UpdatePlayer: 'Update Player',
    InvitePlayervia: 'Invite Player via',
    TeamQRCode: 'Team QR Code',
    AskScanQr: 'Ask Players to Scan this QR Code.',
    Share: 'Share',
    ManuallyaddPlayer: 'Manually add Player',
    AddPhoneNumberorEmail: 'Add Via Phone Number or Email',
    AddPlayerDetails: 'Add Player Details',
    UpdatePlayerDetails: 'Update Player Details',
    StartInnings: 'Start Innings',
    NextOver: 'Next Over',
    NextInning: 'Next Inning',
    MatchComplete: 'Match Complete',
    MatchRunning: 'Match Running....',
    PlayeroftheMatch: 'Player of the Match',
    BestBatter: 'Best Batter',
    BestBowler: 'Best Bowler',
    AddTeamLogo: 'Add Your Team Logo',
    AddTeam: 'Add Team',
    EditTeam: 'Update Team',
    TeamLink: 'TeamLink',
    TeamLogoRequired: 'Team Logo is required',
    AddTeamFromNetwork: 'Quickly Add teams From Your Network',
    ErrorFillOutAllFields: 'Please fill out all required fields.',
    ErrorTournamentBanner: 'Tournament Banner is required',
    ErrorTournamentProfileImage: 'Tournament Profile Image is required',
    ErrorFailedRegisterTryAgain: 'Failed to register the tournament. Please try again.',
    ErrorSomethingWrongTryAgain: 'Something went wrong. Please try again.',
    AddTornamentBanner: 'Add Your Tournaments Banner',
    TournamentBanner: 'tournament_banner',
    TournamentDetails: 'Tournament Details',
    NeedTeamTournament: 'Because you Need Teams For Your Tournament',
    TournamentImage: 'tournament_image',
    TournamentStartDate: 'tournament_start_date',
    AnyAdditionalDetails: 'Any Additional Details?',
    AddMoreDetails: 'Add More Details Like Prizes, Awards Entry Fees, Rules, Etc.',
    AdditionalDetails: 'additional_details',
    DoYouNeedMoreTeam: 'Do You Need More Teams For Your Tournaments?',
    NeedMoreTeams: 'need_more_teams',
    InformPlayerPreviousTournament: 'Inform All The Players Of My Previous Tournaments.',
    PreviousInform: 'previous_inform',
    DoYouNeedOfficials: 'Do You Need Officials? (e.g. Umpire, Scorer)',
    NeedOfficials: 'need_official',
    CreateTournament: 'Create Tournament',
    Continue: 'Continue',
    TournamentRegistered: 'Tournament Registered',
    ContinueCompleteSetup: 'Continue to Complete The Setup',
    StartOrScheduleMatchesSuggestion: 'Quickly start or schedule matches with ease. Get personalized suggestions based on your preferences',
    MatchGuide: 'Match Guide',
    ScheduleMatch: 'Schedule Match',
    EditMatch: 'Update Match',
    AutoScheduleMatch: 'Auto Schedule Match',
    TournamentQr: 'Tournament QR Code',
    TournamentQrDesc: 'Let Cricketers Find Tournament Easily With This QR Code.',
    showmatch: 'Show Match',
    mvp: 'MVP (Most Valuable Player)',
    pointTableDataNotAvailable: 'Point Table Data Is Not Available',
    LeaderBoardDataNotAvailable: 'Leaderboard Data Is Not Available',
    TeamsDataNotAvailable: 'Teams Data Is Not Available',
    nextoveralert: 'Please Select Next Over',
    tournamentDetails: 'Tournament Details'
}
