import Match from "./(page)";

export const metadata = {
    title: "Live Match",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }) {
    return (
      <>
      <Match />
      {children}
      </>
    )
  }